# Build settings
markdown: kramdown
permalink: pretty

encoding: utf-8
highlighter: rouge

port: 3000

include: ["_includes/work"]

sass:
  sass_dir: assets/css
  style: :nested


# Excludes
exclude: ['node_modules','Gruntfile.js','package.json']